name: CI

on:
  push:
    branches:
    - master
    - github-workflow
  pull_request:
    branches:
    - master
jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout latest
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.*

    - name: Install dependencies
      run: dotnet restore
    
    - name: Signing Key
      id: write_sign_key_file
      uses: timheuer/base64-to-file@v1
      with:
        fileName: 'Key.snk'
        encodedString: ${{ secrets.SIGNING_KEY }} 

    - name: Build
      run: dotnet build --configuration Release --no-restore
      env:
        SignAssembly: true
        AssemblyOriginatorKeyFile: ${{ steps.write_sign_key_file.outputs.filePath }}

    - name: Upload Artificats
      uses: actions/upload-artifact@v4
      with:
        name: TestBinaries
        path: test/**/bin/*
  
  UnitTest:
    name: Run Unit Tests
    needs: Build
    strategy:
      matrix:
        os:
        - 'ubuntu-latest'
        - 'windows-latest'
        test:
        - 'ACMESharp.UnitTests'
        - 'PKISharp.SimplePKI.UnitTests'
        - 'ACMESharp.MockServer.UnitTests'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout latest
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: TestBinaries
      - name: Test (${{ matrix.test }})
        if: ${{ !cancelled() }}
        run: dotnet test --verbosity normal --logger "trx;LogFileName=${{ matrix.test }}-${{ matrix.os }}.trx" --results-directory coverage ${{ matrix.test }}/bin/Release/net8.0/${{ matrix.test }}.dll
      - uses: dorny/test-reporter@v1
        if: success() || failure()        # run this step even if previous step failed
        with:
          name: Test Result (${{ matrix.test }}-${{ matrix.os }})" 
          path: coverage/*.trx
          reporter: dotnet-trx
